[package]
name = "libfmod_ext"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.3", features = ["rb-sys-interop"] }
libfmod = "2.2.603"
paste = "1.0.9"
rb-sys = "0.9.41"
once_cell = "1.16.0"
parking_lot = "0.12.1"
